version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=prod
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: quaiantique
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    ports:
      - "3306:3306"
