# Définition des services utilisés par le projet
services:
  app:
    type: php:8.1-fpm
    disk: 1024
    commands:
      start: "php-fpm"
  mysql:
    type: mysql:10.4

# Définition des routes HTTP exposées par l’application
routes:
  "/":
    type: upstream
    upstream: "app:http"
