applications:
  symfony:
    type: "php:8.1"
    source:
      root: public
    relationships:
      mysql:
        service: mysql
        endpoint: mysql

services:
  mysql:
    type: "mysql:8.0"

routes:
  "https://{default}/":
    type: upstream
    upstream: symfony:http
