applications:
  symfony:
    type: "php:8.1"
    source:
      root: .
    relationships:
      mariadb:
        service: mariadb
        endpoint: mysql

services:
  mariadb:
    type: mariadb:11.8

routes:
  "https://{default}/":
    type: upstream
    upstream: symfony:http
